### ISSUE TITLE
is:issue is:open 菜单管理里的权限路由如何新增

### ISSUE THREAD

**Issue by zyj010zyj** [nineaiyu/xadmin-server#1]
![Snipaste_2024-03-14_17-23-52](https://github.com/nineaiyu/xadmin-server/assets/142365349/b615bca0-6d6f-4daf-aea4-0a4894c39c59)

我大概阅读了前后端代码 貌似只有从数据库内读取部分数据 新增路由权限选项是直接在数据库内操作吗?
即使直接在数据库中的path字段添加了权限路由  但在页面的下拉框内还是找不到对应的选项

**Comment by nineaiyu** [comment]
页面的 权限路由 是系统自动生成的，通过 ```common.core.utils.get_all_url_dict```这个方法自动生成，不用自己添加

**Comment by zyj010zyj** [comment]
感谢

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年03月16日 20:31 |
| 收件人 | nineaiyu/xadmin-server ***@***.***> |
| 抄送人 | Ajlong ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [nineaiyu/xadmin-server] is:issue is:open 菜单管理里的权限路由如何新增 (Issue #1) |

页面的 权限路由 是系统自动生成的，通过 common.core.utils.get_all_url_dict这个方法自动生成，不用自己添加
