### ISSUE TITLE
服务端项目必须运行在linux系统上吗

### ISSUE THREAD

**Issue by MYWpro** [nineaiyu/xadmin-server#10]
请问我能否在本地windows运行服务端，我在windows系统运行时daemon部分出现了报错，请问有什么解决办法吗

**Comment by MYWpro** [comment]
> 请问我能否在本地windows运行服务端，我在windows系统运行时daemon部分出现了报错，请问有什么解决办法吗
最后的报错显示 ModuleNotFoundError: No module named 'pwd'

**Comment by nineaiyu** [comment]
[参考文档 windows环境启动部署 ](https://github.com/nineaiyu/xadmin-server/blob/main/README.md#bwindows-%E7%8E%AF%E5%A2%83%E7%9B%B4%E6%8E%A5%E5%90%AF%E5%8A%A8)
