### ISSUE TITLE
celery 定时任务启动后前台无法加载对应的页面

### ISSUE THREAD

**Issue by taoweidong** [nineaiyu/xadmin-server#11]
使用如下服务启动后：
python manage.py runserver 0.0.0.0:8896
python -m celery -A server flower -logging=info --url_prefix=/api/flower --auto_refresh=False  --address=127.0.0.1 --port=5566
python -m celery -A server beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler --max-interval 60
python -m celery -A server worker -P prefork -l INFO --autoscale 10,3 -Q celery --heartbeat-interval 10 -n celery@%h --without-mingle

无法在前端页面通过：http://127.0.0.1:5566/api/flower

麻烦抽空提供一个详细的指导呢？感谢作者

**Comment by nineaiyu** [comment]
这个我已经找了好多资料，也在flower仓库寻找解决方案，暂时未找到可以在Windows上面正常运行方法，请使用Linux环境开发部署
