### ISSUE TITLE
⚠️ Windows上面无法正常运行celery flower，导致任务监控无法打开，请使用Linux环境开发部署

### ISSUE THREAD

**Issue by nineaiyu** [nineaiyu/xadmin-server#12]
⚠️ Windows上面无法正常运行celery flower，请使用Linux环境开发部署

**Comment by MYWpro** [comment]
请问celery flower是否涉及到项目关键内容，我能否删除celery flower相关部分，以求在windows上运行，因为我实在不想从零开始开发这个后端

**Comment by nineaiyu** [comment]
> 请问celery flower是否涉及到项目关键内容，我能否删除celery flower相关部分或者不启动celery flower，以求在windows上运行，因为我实在不想从零开始开发这个后端

开发期间无需运行celery等服务，celery服务目前主要时清理一下脏数据，不启动也不影响是用
