### ISSUE TITLE
[Feature] 希望能添加为用户设置多个部门以及为部门设置负责人的需求

### ISSUE THREAD

**Issue by trajectoryend** [nineaiyu/xadmin-server#17]
## 功能名称
为用户设置多个部门以及为部门设置负责人的功能

## 功能描述
希望能够新增为用户设置多个部门以及为部门设置负责人的需求的功能

## 用户故事
真实情况中，人员可能隶属于多个部门。

如下图，企业微信可以为人员设置多个部门，并可以选其中一个部门为主部门

![image](https://github.com/nineaiyu/xadmin-server/assets/168240719/43a3f95e-48d1-4bac-857f-182f4df63f61)

部门中也可以设置多个人为本部门负责人，如下图：

![image](https://github.com/nineaiyu/xadmin-server/assets/168240719/551b118a-7bc4-4382-b8fc-1dc458d27f07)

新增这个功能后，可以用于做审批流的特定场景下使用，获取对应部门下的负责人进行审批。

望采纳~~

**Comment by nineaiyu** [comment]
```用户设置多个部门``` 这个可能会出现数据归属问题，正在考虑实现方案, 如果你有好的方案，也可以在此讨论

**Comment by trajectoryend** [comment]
大佬，看下这个方案是否可行：
将`UserInfo.dept`换成下面这个表：
```

 class UserInfoToDeptInfo(DbAuditModel):
     to_user_info = models.ForeignKey(to='UserInfo', on_delete=models.CASCADE, verbose_name="用户信息")
     to_dept_info = models.ForeignKey(to='DeptInfo', on_delete=models.CASCADE, verbose_name="部门信息")
     is_master = models.BooleanField(verbose_name="是否主部门", default=False)
     is_active = models.BooleanField(verbose_name="是否启用", default=True)

     class Meta:
         verbose_name = "用户所属部门"
         verbose_name_plural = "用户所属部门"
         ordering = ("-date_joined",)
         unique_together = ('to_user_info', 'to_dept_info', 'is_master')
```
然后数据归属方面：匹配数据的所属部门是否in用户所属的所有部门

**Comment by nineaiyu** [comment]
多部门有点问题，后期再考虑开发，你可以参考 这个分支  https://github.com/nineaiyu/xadmin-server/tree/new-dept
