### ISSUE TITLE
页面迁移没有生效

### ISSUE THREAD

**Issue by sayeo7** [nineaiyu/xadmin-server#19]
把消息中心的页面复制到一个新的路由页面之后  消息中心页面并没有正常显示，请问是有什么检验规则（尝试迁移其他页面也一样）

**Comment by nineaiyu** [comment]
需要修改下菜单中的消息中心的相关配置
![image](https://github.com/nineaiyu/xadmin-server/assets/19207867/97ca5a0a-0213-4bef-92a6-549c0239830b)

**Comment by sayeo7** [comment]
这个配置已经修改，组件名称对的上路由name，路由地址对的上路由path，组件路径更加view下的文件路径读取，尝试过用静态路由实现也不行，新页面内容更改自定义输入内容路由是正常跳转且正常显示内容，直接使用复制过来的页面，跳转进去这个页面显示空白，跳转走就报错
![git](https://github.com/nineaiyu/xadmin-server/assets/92789167/6d4398b1-423c-46ca-8c3d-f1123dc9e3b7)
