### ISSUE TITLE
[Feature] 关于数据的可见范围、可编辑范围的控制需求

### ISSUE THREAD

**Issue by trajectoryend** [nineaiyu/xadmin-server#22]
## 用户故事
数据归属有时候会归属于多个部门以及多人，甚至查看和编辑都是分属不同组和人员的

打个比方有一条数据，3个部门可以看到，其中2个部门可以编辑，除了部门外，另外3个人可以看到，其中俩个人可以编辑，如下：

a部门、b部门、c部门、张三、李四、王五可以看这条数据。
但是只有a部门、b部门、张三、李四可以修改这条数据。

我的理解是：
当前要实现上方需求，需要基于数据在数据权限中定义id_exact具体的值来选中具体数据， 然后找到对应的用户去设置此数据权限。

不知我理解的当前项目是否是这样运行的。

此处有两个疑问：
1. 数据权限的数据量较大的时候，此设置会过于繁琐
2. 数据权限的数据量大了之后，针对数据鉴权会不会过慢

```
class DbAuditModel(DbBaseModel):
    creator = models.ForeignKey(to=settings.AUTH_USER_MODEL, related_query_name='creator_query', null=True, blank=True,
                                verbose_name='创建人', on_delete=models.SET_NULL, related_name='+')
    modifier = models.ForeignKey(to=settings.AUTH_USER_MODEL, related_query_name='modifier_query', null=True,
                                 blank=True, verbose_name='修改人', on_delete=models.SET_NULL, related_name='+')
    dept_belong = models.ForeignKey(to="system.DeptInfo", related_query_name='dept_belong_query', null=True, blank=True,
                                    verbose_name='数据归属部门', on_delete=models.SET_NULL, related_name='+')

    class Meta:
        abstract = True
```
建议新增几个字段
1. 数据的可见部门：ManyToMany类型，用于控制哪些部门可以看到这些数据。
2. 数据的可见人员：ManyToMany类型，用于控制哪些人员可以看到这些数据。
3. 数据的可编辑部门：ManyToMany类型，用于控制哪些部门可以编辑这些数据。
4. 数据的可编辑人员：ManyToMany类型，用于控制哪些人员可以看到这些数据。

然后在数据新增的时候，都添加一个选择对应可见人员、可编辑人员的选项（默认值为当前用户，以及当前用户所属的所有部门，用户可以点选修改），如下图，只列出了可见范围设置：
![image](https://github.com/nineaiyu/xadmin-server/assets/168240719/f19d3bf9-0346-4d96-a45e-c687d744b77e)

这样就可以通过对这4个字段来校验用户是否具有查看、编辑权限
判定逻辑：
1. 判断当前用户是否在可见、可编辑人员列表里，分别返回是否可见、可编辑
2. 判断当前用户的所属部门列表是否与可见、可编辑部门的列表有交集，分别返回是否可见、可编辑

或者是否是我理解项目有问题，目前可以通过其他配置解决此问题？

望回复~

**Comment by nineaiyu** [comment]
你好，上面想法还是挺不错的，但是上述需求仅针对某些业务表，不适合放到通用的DbAuditModel模型中，你可以自行针对某些业务使用
