### ISSUE TITLE
bug反馈

### ISSUE THREAD

**Issue by piscesmax** [nineaiyu/xadmin-server#23]
1、部门管理中，归属部门为空的行，列表中状态开关切换报错；
`parent = BasePrimaryKeyRelatedField(queryset=models.DeptInfo.objects, allow_null=True)`
修改为
`parent = BasePrimaryKeyRelatedField(queryset=models.DeptInfo.objects, allow_null=True, required=False)`
后正常；

2、角色权限、数据权限，列表中状态开关切换报错；
暂不知道上述修改有啥影响，其他没看，感觉类似的功能似乎都可能存在问题。

**Comment by nineaiyu** [comment]
非常感觉你的反馈，这个是patch数据校验问题，下个版本修复
