### ISSUE TITLE
权限访问问题

### ISSUE THREAD

**Issue by zyj010zyj** [nineaiyu/xadmin-server#24]
1.我创建了一个普通用户 仅查看权限   以及管理员   可操作全部数据     但是我发现在查看测试数据时无法正常显示已新增数据, 观察后台日志发现他会默认在查询时传参id=000000      如下

SELECT COUNT(*) AS `__count` FROM `XXXXXXX` WHERE (`XXXXXXX`.`id` = '00000000000000000000000000000000' OR `XXXXXXX`.`id` = '00000000000000000000000000000000'); args=('00000000000000000000000000000000', '00000000000000000000000000000000'); alias=default

在common/core的filter.py文件中   的 permission = DataPermission.objects.filter(is_active=True).filter(deptinfo=p_dept_obj).filter(dq)这一步出现的上面查询条件

但是当我使用超级用户访问页面的时候 数据就会正常显示了 
![1](https://github.com/nineaiyu/xadmin-server/assets/142365349/22cb7623-1939-4edc-9ef1-3af92d6950c8)
![2](https://github.com/nineaiyu/xadmin-server/assets/142365349/800c4d0a-618d-47fe-aa2f-9df78efeabef)
![3](https://github.com/nineaiyu/xadmin-server/assets/142365349/b7dbf78e-e020-4025-8725-df6c7464c475)
![4](https://github.com/nineaiyu/xadmin-server/assets/142365349/4912e377-0f3a-4453-a558-308100c68657)
![5](https://github.com/nineaiyu/xadmin-server/assets/142365349/fec75238-9b82-4f24-a854-1c57c78f5af1)
![6](https://github.com/nineaiyu/xadmin-server/assets/142365349/0e3d052d-f5a2-4b61-85c8-25b6d14d27bd)

2. 菜单管理--新增--权限中的权限路由有些问题  在我新创建一个模块用于开发  例如A模块  下面的 a,b,c三个接口 访问路径为A/a  A/b  A/c   此时的权限路由有时会没有a,b,c的选项 需重复启动多次 
   另外 当可以选择以后 它显示的是没有A这个开头的  也就是直接是a/  b/  c/ 这样在common/core的permission文件中的if p_data.get('method') == request.method and re.match(f"/{p_data.get('path')}", url):这一步  会对比失败  从而导致显示权限不足的错误   现在解决办法是手动去表中修改他的权限路由 将他改为A/a就可以正常访问了

**Comment by nineaiyu** [comment]
你目前是用的xadmin-server 是哪个版本？权限路由是服务器实时获取了，理论上是不用重启。

数据权限是继承关系，需要从上面的部门一步一步继承，如果你直接想要所有的数据权限，可以直接将这个权限设置在用户上面

**Comment by zyj010zyj** [comment]
使用的是以前3 4月份的版本  也使用过2.1.0   我在想是不是我新创建的模块路由写法跟system的有些不一样导致的 我使用的是router = DefaultRouter()    我尝试一下逐步继承权限

**Comment by nineaiyu** [comment]
路由是通过 ```common.core.utils.get_all_url_dict``` 这个方法自动获取，正常django能加载的路由，这里都能获取到对应的路由

**Comment by zyj010zyj** [comment]
对 就是在这里获取路由的时候 会少了前缀A 直接把abc三个子路由获取到了

**Comment by nineaiyu** [comment]
你试一下最新版本代码，看下是否有上面说的路由获取不到问题
