### ISSUE TITLE
feat: 根据后端接口自动生成前端代码

### ISSUE THREAD

**Issue by lihuacai168** [nineaiyu/xadmin-server#26]
如果后端的接口已经写好了。
感觉可以直接生成前端的代码，因为前端代码非常多都是类似的。
直接生成，这样就可以避免手动写很多重复的代码。
希望可以增加这个功能。
<img width="1678" alt="image" src="https://github.com/nineaiyu/xadmin-server/assets/11568297/da0adb85-1db0-49c0-adca-d7ade639ad4f">

**Comment by nineaiyu** [comment]
无法自动生成，只能尽量减少重复代码，目前优化了一版
