### ISSUE TITLE
demo权限设置问题

### ISSUE THREAD

**Issue by TNT-DG** [nineaiyu/xadmin-server#28]
你好，我在按照demo教程创建了图书管理页面后，新建了一个普通用户，并给它设置了角色和数据权限，但是查询图书列表返回的结果是空的，没整明白怎么配置的。但是用初始的管理员账号查询是没有问题的。
![image](https://github.com/nineaiyu/xadmin-server/assets/29853150/9cb39e49-4acd-4fa0-b501-3a9adfa508f5)
![image](https://github.com/nineaiyu/xadmin-server/assets/29853150/bf04eac5-fc59-4089-8e83-f1d6fcbb9072)
![image](https://github.com/nineaiyu/xadmin-server/assets/29853150/91f1213b-0465-4cf7-85ad-bef7699a152d)
![image](https://github.com/nineaiyu/xadmin-server/assets/29853150/dcb14955-d2a3-4a38-b599-94b73526a977)

**Comment by nineaiyu** [comment]
书籍权限不对，你需要添加书籍的权限，而不是角色的权限，可以参考下最新文档：  https://docs.dvcloud.xin/example/new-app-data-permission.html
