### ISSUE TITLE
一点小BUG

### ISSUE THREAD

**Issue by casuallyone** [nineaiyu/xadmin-server#37]
1.部分请求发送时出现跨域问题
![CORS](https://github.com/user-attachments/assets/d51083cd-5951-4f5f-85e8-df628345424c)
原因：后端返回响应HEARDER中相应CORS字段与请求不匹配
修复:编辑settings.py 在CORS_ALLOW_METHODS增加PATCH方法:
CORS_ALLOW_METHODS = (
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
)
生产环境部署时一般不存在跨域问题

2.最新版本中common.utils.swagger.py文件缺失
原因：可能放入了.gitignore中未提交
修复：从上一版本拷贝.

**Comment by nineaiyu** [comment]
感谢反馈，已经修复
