### ISSUE TITLE
swagger生成接口文档时未认证401

### ISSUE THREAD

**Issue by casuallyone** [nineaiyu/xadmin-server#39]
通过前端打开接口文档时，后端进行处理时做了基于用户名的登录，但系统使用JWT认证，所以需要从登录请求头中获取Bearer信息并手动点击认证
![auth](https://github.com/user-attachments/assets/432df4cb-78c1-4a49-a041-77a7ed85f6fa)
会造成接口测试时登录繁琐且不改动JWT access token超时时间时操作窗口期过短，能否在点击接口文档时实现自动填写authorize的认证信息并及时更新？

**Comment by nineaiyu** [comment]
这个授权暂时解决不了，可以通过使用后端域名 + /api-docs/login/ 进行访问，比如demo的访问地址：https://xadmin.dvcloud.xin/api-docs/login/
