### ISSUE TITLE
静态资源报错

### ISSUE THREAD

**Issue by BA7IEE** [nineaiyu/xadmin-server#8]
<img width="1527" alt="iShot_2024-04-10_00 21 39" src="https://github.com/nineaiyu/xadmin-server/assets/32892836/ffa2ccc3-c92a-4581-a43a-a84d5a5c9e29">

服务应该跑起来了。css js加载不到 没找到原因

**Comment by nineaiyu** [comment]
我这里暂时没有遇到，你这种情况是怎么出现的？

**Comment by BA7IEE** [comment]
> 我这里暂时没有遇到，你这种情况是怎么出现的？

我就是拉倒本地  运行的  没有改代码

**Comment by nineaiyu** [comment]
如果要使用Django自带的admin ，建议使用接口服务的地址直接访问，不要通过前端代理访问
